package com.horse;

public class HorseImage {
	
	String [] run1 = {
			"                                               ...`                   ",
			"                                       ```    /s/:-.                  ",
			"                                   ``-::+o/---/hdyo`                  ",
			"                                  ```.:::ss/-:o:/:`      `..`         ",
			"                                  ``.-.-/os/sy-    `..:oydhyys/`      ",
			"                                  `..``` ``:::  ./shmmdmmddhydhs`     ",
			"                                      ``-.`..-/oosdmdhhhyyyhmdshy     ",
			"                      .:/+//:-.````.`   :o/:`.ydhysosyhddmNNhshdm/    ",
			"            .:/oyyhssyhhhddmmdyo://://+/+hNm+:yhh+/syyhmNyyyhymddh`   ",
			"          -yhhdmdyoo/+sohdmmdhds/yd:::/ohmy+-/hyyyssydNh-  .:ydddms   ",
			"  `//+/-.odddmyh-hyhhhhyhhdmdhds-/d:::syhho:-+dmdhssym-       :hmdh:  ",
			"  ./ssyh+dhddhyo:mmmmdhyhddmNddhooyso++/yNd/:+ddmmmdmh         .:..   ",
			"   -yhdhmmy+-``  mmmmNdhdmmmNNmdmdhhhdmmdmdmNmddddmmN+                ",
			"     .+s+`      `mNmdmNNNNmmosdNNmmmNNNNdhdmNNmdddmyho:-.             ",
			"                /dNNmdNmdmd-   `-/oyhmNNmmmdNmdyhNddmmNdhy+y/         ",
			"              `+dmh/ /mddh-           `.-::-.`  `oNNm:..``-+do`       ",
			"             .ody-   ommm:                        -hmh`      oh:      ",
			"            +hy-    `mNN/                          `yNh`      +d+     ",
			"          :dh:      sddo                             +N+      `oy     ",
			"        -yNo        `sN/                              om.     `/s     ",
			"       `sd-           +N:                             `yd-            ",
			"      `/h-             +N/                             .oh:           ",
			"       ./               /yh+`                            -o+.         ",
			"                    `````...````````````````````````                  "
	};
	
	String [] run2 = {
			"                                              -os+.                   ",
			"                                    .--...`` .hhddy`                  ",
			"                                  ``.-::-----:/sys-  ::y+++/`         ",
			"                                 .`-/////::/+o::..::sNNmdhdyy+`       ",
			"                                  -+:..-/::/+--/dmmmddhyyhhhhhh:      ",
			"                         `.--.` -.-`.--:o++ohdmdmdhhhhhdmmddhyhy-.    ",
			"                      :ohdddhhhy+/+s++/ohdddmNmdhhdhyhdmdmdmddyyho-`  ",
			"                  `-ohhddhhhddhy/////syhmmddhyhyhyhddddmo...-/ohddy-  ",
			"               `+hdhhhddddhhhdh+////+oymdhddhyyyhmmmdmd-       `:/-   ",
			"         `-:-oyddNdyhdhmmdysyhy/////oohyhhhhhhhhhhdmmd.               ",
			"    ``-..ymmmdmhsdmdmmmydmmdssmdyso+/shymdyhhdhhhydmd+                ",
			"  :/oydddmmNmNy---:-/hmmmNmmhymmmmddddddmmdhmdhhyyddd`                ",
			"   :shdmNmmNNm`       ./odmmdhMNddddddddmmmddmhhyhhy-                 ",
			"    `:/+yhhy+`           -mddNNds`:oshdmmmmdhshhdmddys+-`             ",
			"                         -NmhdNmd`    `-/hmds/+dhssssoohh/            ",
			"                         ydhh-mmd-        -ohhs:       .do            ",
			"                         -+yyy/shy`   `ss+`  /yy/`     sh`            ",
			"                               `-/+.   `/so-:osmh.    oh/             ",
			"                                 .sy+`    -/:-``    ./h/              ",
			"                                  .syy/-`           .s+               ",
			"                                    `.-yy+.                           ",
			"                 ``````````````````````..`````````````                ",
			"                                                                      "
	};
	
	
	String []horseIm={
			"                                                                -=._",
			"                                                            .oo0P~GPjo.",
			"                                                       .o0o0000P'.?P   `jo.'.",
			"                                                __     .000000P.;'   .dP.dPo) ,",
			"                                           . '0000oo.00d00b.P'        X^V  P<<",
			"                                             '~~',`0.d'd;V'.8      '(       o)K",
			"                       . -  ~  ~  -  .   _  _ - '  .d'd(   8'     ' :      .' X",
			"        _.oo00oo._ . `                             V' `?   ?'  .'   ;    .'",
			"     .C000000000000o=K                             '   `  `   `.   {  .  ;",
			"    C00000000000P~'   '             `                          )-.  `'J o,",
			"    `?000000P~' `     '              '                         ;. `.   `'",
			"      )0000D'   `      `            .'                       .'_.`-.`.",
			"  .oo00000P'     `.'`.  `.                           `.    .'       ) `.",
			".o00P~~'  .   - '  . - . _`(      .'` `  -  .  -  ` - -`.  ' _ .-   '`. ,",
			"  ~j   .'         '   _          .'                      `'~     ' ' /'-,",
			"      . .' ' '  ' `  `  `~'`~--~'                              .' '  `-.,",
			"      , ,          ` `                                      .',. '",
			"      . .           ` `                                     U,'",
			"    . '.'         _ .`.`",
			"  ,-,'           bd_.'",
			"  U,'"

	};
	
/*	String[]horseid={
			"                      ~~%%%%%%%%_,_,",
			"                   ~~%%%%%%%%%-'/./",
			"                 ~~%%%%%%%-'   /  `.",
			"              ~~%%%%%%%%'  .     ,__;",
			"            ~~%%%%%%%%'   :       aOa",
			"          ~~%%%%%%%%'    :          `.",
			"       ~~%%%%%%%%'       `. _,        '",
			"    ~~%%%%%%%%'          .'`-._        `.",
			" ~~%%%%%%%%%'           :     `-.     (,;",
			"~~%%%%%%%%'             :         `._*_.'",
			"~~%%jgs%%'              ;"
				
				
		};*/
	
	String [] hormain={
			"Yb,     ________",
			" Y8baadP'''''''''''''Yba,_",
			"aaadP''             `''Yb,",
			"`Y8(                    `'Yb,",
			"`Y,                      `Yba,",
			"  Y,  (O)                   `Yba,",
			"  `Y,                          ''Yba,________,,aaddddbbbaa,,____,aa,_",
			"   `Y,       ,aa                   `''''''''''''          ``''''''  'Y,",
			"     Y,      d'8                                                'Ya   `Y,",
			"     `b      8 8                  ┌ 경마게임─┐                  `Y,   Y,",
			"      Ya o  ,8 8                  │           │                    b   `b",
			"       Yb,_,dP 8                  │1. 로그인  │                    Y    8",
			"        `''''  Y                  │2. 회원가입│                    8    8",
			"               I,                 │3. 회원찾기│                   8    8",
			"               `b                 │4. 회원탈퇴│                   P    [",
			"                `b                │5. 종료    │                  d'    [",
			"                 d                └─────★                  ,P     [",
			"               ,d'    ,PY,         ,P'YaaaaaaP'Ybaaa,,_           d'     [",
			"              d'    ,P'  Y,        d'           8'  `''db,       d'      8",
			"             d'   ,P'    `Y,       8            I,     d''b,     8a      P",
			"            d(    (       `Y,      P            `b    ,P  `Y,    8`Ya___d'",
			"            'Y,   'b,      `Y,    ,I             8    d'   `8    8  `''''",
			"              'Y,   'b,  __ `8,   d'            ,8   ,P     8    8",
			"                'Y,   'bd88b `b   8             I'   d'     Y,   8",
			"                  'Y,    888b 8   8             8   ,P      `b   8",
			"                    'Ya,,d888b8   P            d'  ,P'       8   Y,",
			"                       `'''',d'  ,I        ,adPb__aP'        Y   `b",
			"                         ,a8P,__aP'       d888888P'         ,d    8",
			"                        d8888888'         88888888       ,d888bbaaP",
			"                        88888888                         88888888'"
			
			
	};
	
	String []airplane={
			"  ,--.				도	박",
			"  $ _$_     			상	담",	
			"  _$/_|_$____.'$",
			"-(___.--._____(			국	번	없	이",
			"     $   $			1	3	6	6 ",
			"      $   $",
			"       `--'"
	};	
	
	String []running1={
			"                                                                    ```                             ",
			"                                                                  `/:---.`                          ",
			"                                                       ```````   `/os/::-.                          ",
			"                                                    `-:::/+//-----+hdhyy+.                          ",
			"                                                 ````.-:-:oss--.-://dhos.                           ",
			"                                                `````.-::-+sso+::/o/---`        ``--:-`             ",
			"                                                ` `.---.:/+yy+ssos:       `  `-+oydhhsys-.          ",
			"                                                 -....```.--:::/y+     `-/yssyhhmmddhhdddh+`        ",
			"                                                  ``..``` ```::--.```:+shdmmmdmmmdddhyyhhhy/`       ",
			"                                                     ```...``..---:/o+ohhmmmdhhhysysshmmdsyh+       ",
			"                                 `````                   .:-...  /ydhhdddhhhsyhhhdmNNNdyyyddd.      ",
			"                       ````   `./osyyyysso+::...`.:-.`   :yss+/.`.hdhyo++//oyhddhhmmNmyohddNNs      ",
			"                  .-/+oyyhhyosyhdhhddmdmmmhyy::::--:///s/+ohNNm+::hhdh+:+syysydmNmhyhyhshmdmmd-     ",
			"               `+yyyhdmddhyyyooyhyyhhdmmmdddd:/hdh:::::/+ohNdhs::+yyyyhsosyydmNNh/ .:+yhhmhhdmh`    ",
			"     ..``     :yhdyddmNyos++:/+oooydddmmdyddd::/hd::::/oyhmmo/---hhhhyssssyhmNh/       -dhdhmmdo    ",
			"   `///o+/:-`oddhdmdyds.hyyhdhhhdhyhydmmdyddd:::yd::::+oyyhsh+---ydmmmhyosyhm/           /hdmmhd:   ",
			"   `-+ooohs++dhymmhhoho:NdmmmmdyysyhhddmNddddo:-+s/---/ooymmd+--:ommmmmmdydmm             -ys+s.    ",
			"   `-+yhhsdyhdddddyso/- hmmmmNmhdhyddmNNNmmmdhdddhhddhyyosmNNyosyhdddddmmmNNs                       ",
			"     /hhhdhdmNho:.      ymmmdNNNddhdmmdNNNNmmmmdhhhhddmmmmhdmdNNNmddddddmmNN/                       ",
			"      `.+ydds.          ymmmddmNNNNNNNdNddmNNNNmmmmmNNNNNmhyhdNNNNmddddmdssh:`                      ",
			"        `-.`           `dmNNmddmmmmmmhms``./shmNNNNNNNNNNNhmmhNNNmmdddmNddmdddyy+--..`              ",
			"                      `/dmNNNddNNNddmm+`     ``.:/oyhdmNNNhNNhNNNdhyydNmddmmmNmdddhodho`            ",
			"                     .+hmmmy:`-mdmdhhs              ``.-://oo/::..`` .sNNNNh::::-.-/odms`           ",
			"                    .sdNms.   .mddmms`                                 :mmNm:        `/dh:          ",
			"                  `-oydo.     +mmmmh`                                   .ymNm/         .hho.        ",
			"                 .ssys.      `dNNNd.                                     `oNmm:         .ydd`       ",
			"               `/dmy/`       oNmmm.                                        +mNm`         .ym/       ",
			"              :hNh-         `dmhd+                                          -mN/         -+y+       ",
			"            -smNo`           .sNN/                                           :Nm.        ./h+       ",
			"            dmd/               +Nm.                                           smd.        `-`       ",
			"          ./dh.                 :mm-                                          `ydd-                 ",
			"         `/od-                   :Nm:`                                         .+dy/`               ",
			"          .sy                     ohso/`                                         -oso-              ",
			"           ``               ```````.yhho.``````````````````````````````````       -:/:.             ",
			//"                             ````````````````````````````````````````````        "		
	};
	
	String []running2 = {
			"                                                                    ``                              ",
			"                                                                  :syys/`                           ",
			"                                                    `...`````    /hhhdddo                           ",
			"                                                  `.-::::--.````.:syymhys`    `.  ```               ",
			"                                                `.`.-.-::---::::/-/ssss-`  ./:sds/yos:`             ",
			"                                                .``-//::::+::///oo/+::````-ymNNNdddddhs+`           ",
			"                                                .-+++--:oo:://+so-``-+/ydddmNmddhyyyyhhhy-          ",
			"                                                 .//:---.::::::+::/+ymNNmmdhhhsyyyddhhhhddo.`       ",
			"                                     `````    ```` `-:/:.++/++oydhddmNmdyhhhhhhdmmdddhhyhhhs.`      ",
			"                                ``-+syyhysoo+oo//so:.``.shhooddmmNMmdhyhhyyyhdmmmmmdmhhhhyy/o:.     ",
			"                              `:shddddddhhhhyy////+oshssohdmmmhmmmddhhdddhhhdhmmdddhddhddyhhdh/-`   ",
			"                           `:ohhhdddhhhddhddho///////yoyhdmmdhdyyhhyyhhyhdddddmmh-.`.--/syhyddho-   ",
			"                        :oydhhhddmddhyyyhdhhh////////+yhdmdhhddhyyyyyyhdNmddmmm+          :shhs:    ",
			"                     `+dmmmyyhddddmmdhhdhdhho//////+osoydhhhddhhhyhhymNNmdmmmd:             ``      ",
			"              .--.+sddddmNdyyddhdmmmdhssyhhy////////oohhyhhhhhhhhhhhhhhddmNmm-                      ",
			"          `  ohhhdhyhmmhhdmddmmmsohmmmds++ydhyo+/////odhyhmhyyyhdhhhhhyymmmmo                       ",
			"   ``..-/s+:+mNMMNmNNdoohdNmhmmNNNNmmmNmdyhmmmdddhysoyhhymmdhydhhdhhhyyymddd:                       ",
			"  `:/+syhddmddmmmNNNd..``.-.`/hddmmNNmmmhhhmdmmmmddddddddmmmmhhmddhhhyyhmdds                        ",
			"   `/oyhhdmNMNmmNmNN.         `./syddmmdhyyMNmddmmdddddddmmmmmddmdhhhyydhho`                        ",
			"     `/shhhdmhdNNNN/              `-ymdddhmMmNsshmdddddddmmmmddddmhyhhhhddo-.                       ",
			"       --:/oyyyys+.                 .NddddMMmds `.:+syddmmmmmmdhoyhhddmmdhhyys+-`                   ",
			"            ```                     .NmmdhMNmdd`     ``:/ohmmdho+:oNMmddddddhsdmh:`                 ",
			"                                    odddd.dNmmd:          `:sddhyo+:-.......``.:mmo                 ",
			"                                   `mmdyd/:mmmd+            `.+ydhso-          -dd`                 ",
			"                                    /shddhs+yhhd:      :ooo:`  `:ydho-        .yd+                  ",
			"                                      `.-:.`.-+os-     `+yhh:`  `./hys:      `syy`                  ",
			"                                             `-:+s/.     `-+so:ohhhddy`      /mh/                   ",
			"                                               `/hys/       -//:--..`      -+yh:                    ",
			"                                                 +yyy+-`                   ooho                     ",
			"                                                 `/ooysso:`                -s/                      ",
			"                                                    `../hys+.                                       ",
			"                         ```````````````````````````````/+::-````````````````                       ",
			//"                               `````````````````````````````````````````              ",			
	};
	
	String []over={

			"     ggggggggg   ggggg aaaaaaaaaaaaa      mmmmmmm    mmmmmmm       eeeeeeeeeeee     ",
			"    g:::::::::ggg::::g a::::::::::::a   mm:::::::m  m:::::::mm   ee::::::::::::ee   ",
			"   g:::::::::::::::::g aaaaaaaaa:::::a m::::::::::mm::::::::::m e::::::eeeee:::::ee ",
			"  g::::::ggggg::::::gg          a::::a m::::::::::::::::::::::me::::::e     e:::::e ",
			"  g:::::g     g:::::g    aaaaaaa:::::a m:::::mmm::::::mmm:::::me:::::::eeeee::::::e ",
			"  g:::::g     g:::::g  aa::::::::::::a m::::m   m::::m   m::::me:::::::::::::::::e  ",
			"  g:::::g     g:::::g a::::aaaa::::::a m::::m   m::::m   m::::me::::::eeeeeeeeeee   ",
			"  g::::::g    g:::::ga::::a    a:::::a m::::m   m::::m   m::::me:::::::e            ",
			"  g:::::::ggggg:::::ga::::a    a:::::a m::::m   m::::m   m::::me::::::::e           ",
			"   g::::::::::::::::ga:::::aaaa::::::a m::::m   m::::m   m::::m e::::::::eeeeeeee   ",
			"    gg::::::::::::::g a::::::::::aa:::am::::m   m::::m   m::::m  ee:::::::::::::e   ",
			"      gggggggg::::::g  aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee   ",
			"              g:::::g                                                               ",
			"  gggggg      g:::::g                                                               ",
			"  g:::::gg   gg:::::g                                                               ",
			"   g::::::ggg:::::::g                                                               ",
			"    gg:::::::::::::g                                                                ",
			"      ggg::::::ggg                                                                  ",
			"         gggggg                                                                     ",
			"                                                                                    ",
			"       ooooooooooo vvvvvvv           vvvvvvv eeeeeeeeeeee    rrrrr   rrrrrrrrr      ",
			"     oo:::::::::::oov:::::v         v:::::vee::::::::::::ee  r::::rrr:::::::::r     ",
			"    o:::::::::::::::ov:::::v       v:::::ve::::::eeeee:::::eer:::::::::::::::::r    ",
			"    o:::::ooooo:::::o v:::::v     v:::::ve::::::e     e:::::err::::::rrrrr::::::r   ",
			"    o::::o     o::::o  v:::::v   v:::::v e:::::::eeeee::::::e r:::::r     r:::::r   ",
			"    o::::o     o::::o   v:::::v v:::::v  e:::::::::::::::::e  r:::::r     rrrrrrr   ",
			"    o::::o     o::::o    v:::::v:::::v   e::::::eeeeeeeeeee   r:::::r               ",
			"    o::::o     o::::o     v:::::::::v    e:::::::e            r:::::r               ",
			"    o:::::ooooo:::::o      v:::::::v     e::::::::e           r:::::r               ",
			"    o:::::::::::::::o       v:::::v       e::::::::eeeeeeee   r:::::r               ",
			"     oo:::::::::::oo         v:::v         ee:::::::::::::e   r:::::r               ",
			"       ooooooooooo            vvv            eeeeeeeeeeeeee   rrrrrrr               ",
			"                                                                                    ",
			
	};
	
	String []ready = {
		
			"                                                    ohdhhhy                                         ",
			"                                                    hMNmmNN.`                                       ",
			"                                                  `+yhhsyyh:.                                       ",
			"                                                   -:o+++/+                                         ",
			"                                                   `ydds:-.                                         ",
			"                                                  `smmddd+`                                         ",
			"                                                  /NMNMNdhs`                                        ",
			"                                                  oNMMMMmhd+                                        ",
			"                                                  -NMMMMNmdd                                        ",
			"                                                   mMMMMMmdd:`                 ..-.--:-::.`` `-o:   ",
			"                                                   +MMMMMMmmmhs:.`        ``-:://://::::::/ysdNh.   ",
			"                                                   .mMMMMMMMMNNmdo.``  `.:+/:------------:ohNNo`    ",
			"                                                  `+ymNMMNNhshddd+/+s/o/:::-------:////:/+yyyy+     ",
			"                                               ---ddhmNNNNm-``..-`+ydoyhyo++/:::///++/:-.+y:-:-     ",
			"                                               `smmNddmNmmo.hdy+-+oyd+///ohhy+/////o/-.`:ss/ho.     ",
			"                               `.........```   `sdmdNMMMNd.`.hmd::yyhh+/---odNdyoooy+:-:os+::-      ",
			"                           ``.---------::-:s````smmdmNNmms.```ods`syysoo+/://+syysh/+yoohy:--`      ",
			"                        ``..-::::--::/::-//s     `-odmmmNm/..``/h`:so/+:////:///oys+syyyddhys.      ",
			"        ``     `....+oo:`.::::::-:////+//::s`      `ymmmmMMhos.`s.`s++/-::///++//:`:/+dsysoo:       ",
			"    `.:..//-.-:::://ooo.--:::--://///////:-/-      `.+:++smmdNdoh` o/s/:-:::/++o+    -y/h/:s-       ",
			"   `-+oooo/+oo+//::-  `.::::--://///////:---+`       ``+shhdNMNN:  +o/://://:++o     `/-oo+s-       ",
			"    `./sosssys//o/:-  .::::::::///+//::::---+o/-``````.:dsyNMNN+` -+:-/://://:o:         `          ",
			"    -/+++oshds++yo::  .:://++/:://::-----.-:///+oooooosso+mMd+o+:/+::-::://::::/                    ",
			"   `+s+osshddddhhoo+: ./:/ssoo+/:/+/::---.-+////:::://+syyMNsommh++++::://++:-.:                    ",
			"    /sohdyNNNmNNdyy+/` /++/osysssooooo/:::/+++////////+hhmNdo+mmdo+oo+/://+/:--`                    ",
			"    `/odsdmmNNNmmsy./- `+yho/+oysssooo+++oo++o+++++//+ydhhyo+/mmmsoosso+://:-:.                     ",
			"     /sNydhdNNNNmy++/.  `/sdmdyo+ss++///syo++++oo++++ommmhhoo+NNNy++ssso:-//:`                      ",
			"     /hmddmNmNdmNdso-     :syhh+///:://:.`.-::://///+oyyhhsodhdmdyoooo//::+:-..                     ",
			"   .:+ohmNNNmmmdhyso.      .ss+/:///:-`            ```````:-.....`++++/::o+::://-`                  ",
			"  `:./+ssmmNNmmhsy+.       .//+::++:.                             ++//::-:ooydyyso/`                ",
			"   `.:/+shdNmmmmyhy`      -:://::/.                               s+/:::   `.:+hdmho                ",
			"    -`/+shdmmhmhyyh-    `/yssyhy+.                               .Ns///        `-mNh.               ",
			"     -+oohdmdymdy+:    ./y++osydo.`.`                            +Mdy+`         `mh+                ",
			"     `:s/yydyyds+-     ys+/++:`-::/:-.``                         hmyy-          -yd/                ",
			"      `:/+:sysd+-`     .so++/    `./+/-..                        hmmy           syd-                ",
			"       `.+/+hsy:-       :hsy.       `:///-                       hMN-          /dNN`                ",
			"         :-:+/-`         oo/-         :/:-                      `yM+         `.-++:                 ",
			"                         `///`        oo//                      ./y`        `yy+.`                  ",
			"                          ://:        .ss/                     `....         sso-                   ",
			"                           :--.        `:`                     .++-`         `/-                    ",
			"                           .///:---`                            `-+:--                              ",
			"                            `.-osss+.``````````````````````````` `osss+`                            ",
			"                    ```````````.----.```````...............`..````.----````````````       `    "
			
	};
	
/*	String [] horseid = {
			
			" 88888888888a              a88888888888	",
			" 8         YI              IP         8	",
			" 8         `8,            ,8'         8	",
			" 8          8I            I8          8	",
			" 8          8I            I8          8	",
			" 888     O  8I            I8  O     888	",
			"   8        8I            I8        8		",
			"  ,8       ,8'            `8,       8,		",
			" ,8'      ,8I              I8,      `8,	",
			",8'   O  ,8I'              `I8,  O   `8,	",
			"IP       dP'                `Yb       YI	",
			"8'      d8'                  `8b      `8	",
			"8       I8                    8I       8	",
			"8,      I8,                  ,8I      ,8	",
			"Yb   O  `8b,                ,d8'  O   dP	",
			"`8,      `8b,              ,d8'      ,8'	",
			" Yb       `Yba            adP'       dP	",
			"`8b        `Yba,_    _,adP''        d8'	",
			"  `Yb,        `''YYbbddPP''       ,dP'	    ",
			"   `Yba     O              O     adP'		",
			"     ''Yba,                   ,adP''		",
			"        ''YbaaaaaaaaaaaaaaaaaadP''		",
			"          '''YYba,      ,adPP'''		",
			"              '''YYbbddPP'''		"


	};
	*/
	
	String [] horseid = {
			
			"                                              ``-`                    ",
			"                                          `:shssyo`                   ",
			"                                         /yhsy++oso.`                 ",
			"                                        ohhyyosy/++/::-`              ",
			"                                       /yhddho+o/:-:++/.              ",
			"                  `-:-`                soysss+:.     `                ",
			"                `sddddhs-`..`::.`   `.-ooooso+:-                      ",
			"                hddddo++/+o+++shhhhhhyhshhysso/-                      ",
			"               `mddh-++osssso+//:ohhhhhyyyhysso/-                     ",
			"                mdh+ osoooosooooooyhhhhyssssoosoo                     ",
			"               `mdy- /sooooosyhhhyyyyyyoyysssoo+`                     ",
			"              `hmdo+ohso+//++:/oyhhydyohohhyyso/-`                    ",
			"             -dy+:s//o//:-.       `.:://-.`.:/oso/-.                  ",
			"               ./s+:-                          `:oso/.                ",
			"             :+ho/-                               -yyo/.              ",
			"    .:::///:/dy+:.                                  /hyo:-//:....`    ",
			"    +o::oo+/yh++-`                                  ./oosyooso+/so    ",
			"         .:syoo+++/-.`                         ``-:++/::oyy+-`        ",
			"            .:ossoo+++/::-.``           ``..-://+////oss+-`           ",
			"               `-/osssoo+//++++///////////+//++oosss+:.               ",
			"                   `.:/+ssyyyyyssssssssssssssso+/-.                   ",
			"                         `..-::///+++///:--.`                         " ,
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
			
	};
	
	String [] ending = {
			
			"       .                                                                           ",
			"         z$$$$$e.                         					    ",
			"       .$$$$$$$$$c                                                                 ",
			"       $$$$$$$$$$$.                            회                                  ",
			"      4$$$$$$$$$$$F                             원     게                          ",
			"      ^$$$$$$$$$$$F                              관     임                         ",
			"       *$$$$$$$$$$  ..                            리     제   오                   ",
			"       ^*$$$$$$$$\\e$$$e.                          --    작     류                  ",
			"         '*$$$P'.$$$$$$$c                        최     --    수                   ",
			"                $$$$$$$$$$e.                    보     최    정       l            ",
			"                $$$$$$$$$$$$b.                  근    설    --       l             ",
			"                '*$$$$$$$$$$$$$ee..                  화    황       i         ..   ",
			"                 .$$$$$$$$$$$$$$$$$$eee......eeedec.      병       w       ..      ",
			"                z$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$b.   열      t      d.         ",
			"               z$$$$$''*$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$c      : i      e            ",
			"              d$$$$$'    '*$$$$$$$$$$$$$$$$$$$$$$$$$$$$    찬     n u              ",
			"            .d$$$$P'       ^'*$$$$$$$$$$$$$$$$$$$$$$$$$  협     i                  ",
			"           .$$$$$*            ^'$$$$$$$$$$*$$$$$$$$$$$'     n t                    ",
			"         .z$$$$$'                ''*$$$$$$$$$$$$$$$$$*'  c o                        ",
			"    .zed$$$$$$$'                    ''*$$$$$$$$$$*'                                 ",
			"                                    .d$$$$$$$P'                                    ",
			"                                  .d$$$$$$$*'                                      ",
			"                                z$$$$$$$$'                                         ",
			"                              .$$$$$$$*'                                           ",
			"                              d$$$$$*'                                             ",
			"                             z$$$$'                                                ",
			"                            .$$$$$                                                 "	
			
	};
		
}
